import assert from "node:assert/strict";
import { writeFile } from "node:fs/promises";
import path from "node:path";

export async function verify({page,content,snapshot,dir}) {
 const checks = [];
 const check = (label,value) => { assert.ok(value,label); checks.push(label); console.log("PASS",label); };
 const delay = ms => page.waitForTimeout(ms);
 const search = async query => { await page.keyboard.press("Control+f"); await page.getByRole("textbox",{name:"Find in document",exact:true}).fill(query); await delay(450); };
 const counts = () => page.locator(".search-bar__count").innerText();
 const root = page.locator(".reader-scroll");
 const block = i => page.locator(".code-block").nth(i);
 const validRanges = () => page.evaluate(() => { const ranges = [...CSS.highlights.get("md-reader-search-results")]; return { count:ranges.length, connected:ranges.every(r=>r.startContainer.isConnected&&r.endContainer.isConnected), texts:ranges.map(r=>r.toString()), active:[...CSS.highlights.get("md-reader-search-active")].map(r=>r.toString()) }; });
 check("offscreen code is complete plain text",await block(119).locator("code").evaluate(el=>!el.querySelector(".token")&&el.textContent.includes("needle-119")&&el.textContent.endsWith('active: true };')));
 check("opening highlights only nearby blocks",(await snapshot()).highlights<=2);
 await root.evaluate(el=>el.style.scrollBehavior="auto");
 const geometry = await block(5).evaluate(el=>{const pre=el.querySelector("pre");el.scrollIntoView({block:"center",behavior:"instant"});return {height:el.getBoundingClientRect().height,font:getComputedStyle(pre).font,lineHeight:getComputedStyle(pre).lineHeight,padding:getComputedStyle(pre).padding,tab:getComputedStyle(pre).tabSize};});
 await delay(350);
 const afterGeometry = await block(5).evaluate(el=>{const pre=el.querySelector("pre");window.__savedToken=el.querySelector(".token");return {height:el.getBoundingClientRect().height,font:getComputedStyle(pre).font,lineHeight:getComputedStyle(pre).lineHeight,padding:getComputedStyle(pre).padding,tab:getComputedStyle(pre).tabSize};});
 assert.deepEqual(afterGeometry,geometry);checks.push("plain/highlighted height and typography match");
 const savedCount=(await snapshot()).highlights;
 await block(60).evaluate(el=>el.scrollIntoView({block:"center"}));await delay(350);
 const afterVisit=(await snapshot()).highlights;
 await block(5).evaluate(el=>el.scrollIntoView({block:"center"}));await delay(350);
 check("re-entering preserves highlighted nodes and does not rehighlight",(await snapshot()).highlights===afterVisit&&await block(5).evaluate(el=>el.querySelector(".token")===window.__savedToken));
 check("scrolling highlights new visible blocks",afterVisit>savedCount);
 await block(0).evaluate(el=>el.scrollIntoView({block:"center"}));await delay(300);
 const keyword = block(0).locator(".token.keyword").first();
 const beforeColor=await keyword.evaluate(el=>getComputedStyle(el).color);
 const beforeTheme=(await snapshot()).highlights;
 await page.getByRole("button",{name:/Change theme\./}).click();await delay(350);
 const darkColor=await keyword.evaluate(el=>getComputedStyle(el).color);
 check("theme updates token colors without highlighter execution",beforeColor!==darkColor&&(await snapshot()).highlights===beforeTheme);
 await search("const searchable");
 check("cross-token search finds all 120 matches",(await counts())==="1 / 120");
 let ranges=await validRanges();
 check("search highlights use connected ranges with complete text",ranges.connected&&ranges.count===120&&ranges.texts.every(t=>t==="const searchable")&&ranges.active[0]==="const searchable");
 await page.screenshot({path:path.join(dir,"search-results.png")});
 const beforeSearchTheme=await snapshot();
 await page.getByRole("button",{name:/Change theme\./}).click();await delay(300);
 check("theme switch preserves active search ranges without rebuilding",(await snapshot()).indexBuilds===beforeSearchTheme.indexBuilds&&(await snapshot()).highlights===beforeSearchTheme.highlights&&(await validRanges()).connected&&(await counts())==="1 / 120");
 const builds=(await snapshot()).indexBuilds;
 await root.evaluate(el=>{for(const f of [0.1,0.8,0.2,0.75])el.scrollTop=(el.scrollHeight-el.clientHeight)*f;});await delay(450);
 ranges=await validRanges();
 check("lazy conversion rebuilds search once for a burst",(await snapshot()).indexBuilds-builds===1);
 check("search results survive token conversion",ranges.count===120&&ranges.connected&&(await counts())==="1 / 120");
 check("search rebuilding does not pull manual scroll back to active match",await root.evaluate(el=>el.scrollTop>(el.scrollHeight-el.clientHeight)*0.4));
 const middle=block(59);await middle.evaluate(el=>el.scrollIntoView({block:"center"}));await delay(350);
 const beforeCopy=await snapshot();
 const expectedCopy=await middle.locator("code").textContent();
 await middle.getByRole("button",{name:"Copy code",exact:true}).click();await delay(1800);
 const afterCopy=await snapshot();
 check("copy includes complete code",await page.evaluate(()=>window.__copied)===expectedCopy);
 check("copy feedback does not highlighter-render or rebuild search",beforeCopy.highlights===afterCopy.highlights&&beforeCopy.indexBuilds===afterCopy.indexBuilds);
 await page.getByRole("button",{name:"Next match",exact:true}).click();
 await page.waitForFunction(()=>document.querySelector(".reader-scroll").scrollTop<5000);await delay(250);
 check("next match navigation survives rebuilt index",(await counts())==="2 / 120"&&await root.evaluate(el=>el.scrollTop<5000));
 await page.getByRole("button",{name:"Previous match",exact:true}).click();await delay(300);
 await page.getByRole("button",{name:"Previous match",exact:true}).click();
 await page.waitForFunction(()=>{const el=document.querySelector(".reader-scroll");return el.scrollTop>(el.scrollHeight-el.clientHeight)*0.95;});await delay(250);
 check("previous match wraps and scrolls to last code block",(await counts())==="120 / 120"&&await root.evaluate(el=>el.scrollTop>(el.scrollHeight-el.clientHeight)*0.95));
 await search("active: true");check("search spans punctuation and keywords",(await counts()).endsWith("/ 1920"));
 await search("const");check("search retains 2000-result cap",(await counts()).endsWith("/ 2000+"));
 await page.getByRole("button",{name:"Close search",exact:true}).click();
 await page.getByRole("button",{name:"Edit",exact:true}).click();await delay(350);
 const preview=page.locator(".edit-pane--preview");
 check("preview starts with its own visible code block",await preview.locator(".code-block").first().locator(".token").count()>0&&await preview.locator(".code-block").nth(119).locator(".token").count()===0);
 await preview.evaluate(el=>el.scrollTop=(el.scrollHeight-el.clientHeight)*0.7);await delay(400);
 const previewSnapshot=await snapshot();
 check("preview scrolling highlights its own viewport",await preview.locator(".code-block").nth(84).locator(".token").count()>0);
 const inputCost=await page.locator(".markdown-editor textarea").evaluate((el,content)=>{const set=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,"value").set;const t=performance.now();for(let i=0;i<8;i++){set.call(el,content+`\nlatest ${i}`);el.dispatchEvent(new Event("input",{bubbles:true}));}return performance.now()-t;},content);
 await delay(500);
 check("continuous edits keep latest preview",(await preview.locator(".markdown-body").innerText()).endsWith("latest 7"));
 check("unchanged code in preview is not rehighlighted",(await snapshot()).highlights===previewSnapshot.highlights);
 check("burst edits produce one deferred Markdown parse",(await snapshot()).markdown-previewSnapshot.markdown===1);
 const beforeTyping = await snapshot();
 const typingStarted = Date.now();
 await page.getByRole("textbox",{name:"Markdown editor",exact:true}).press("Control+End");
 await page.getByRole("textbox",{name:"Markdown editor",exact:true}).pressSequentially(" typed",{delay:20});
 const typingMs = Date.now()-typingStarted;
 await delay(400);
 check("real keyboard input updates preview without rehighlighting unchanged code",(await preview.locator(".markdown-body").innerText()).endsWith("latest 7 typed")&&(await snapshot()).highlights===beforeTyping.highlights);
 await preview.evaluate(el=>el.scrollTop=0);await delay(350);
 const replaceEditor=async value=>{await page.locator(".markdown-editor textarea").evaluate((el,value)=>{Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,"value").set.call(el,value);el.dispatchEvent(new Event("input",{bubbles:true}));},value);await delay(450);};
 await replaceEditor(content.replace("needle-0","changed-0"));
 check("changing visible code refreshes highlighted text",(await preview.locator(".code-block").first().locator("code").textContent()).includes("changed-0")&&await preview.locator(".code-block").first().locator(".token").count()>0);
 await replaceEditor(content.replace("```ts","```unknown"));
 check("changing language to unknown falls back to complete plain text",await preview.locator(".code-block").first().locator(".token").count()===0&&(await preview.locator(".code-block").first().locator("code").textContent()).includes("needle-0"));
 await replaceEditor(content.replace("```ts","```js"));
 check("language alias updates highlight grammar",await preview.locator(".code-block").first().locator(".token").count()>0);
 await page.getByRole("button",{name:"Editor",exact:true}).click();await delay(200);
 const onlyEditor=await snapshot();
 await replaceEditor(content+"\neditor only");
 check("editor-only layout still suspends preview rendering",(await snapshot()).markdown===onlyEditor.markdown&&await page.locator(".markdown-body").count()===0);
 await page.getByRole("button",{name:"Preview",exact:true}).click();await delay(350);
 check("preview restores latest draft",(await preview.locator(".markdown-body").innerText()).endsWith("editor only"));
 const sizes = await page.evaluate(()=>{
  const samples=[];
  const bases={typescript:'const item = { name: "test", active: true };\n',json:'{"name":"test", "items":[1,2,3], "active":true}\n',yaml:'name: test\nitems: [1, 2, 3]\nactive: true\n',tsx:'const App = () => <div className="x">{value}</div>;\n',markdown:'# Title\n\n**bold** and [link](https://example.test)\n',powershell:'$item = @{ Name = "test"; Active = $true }; Write-Host $item\n'};
  for(const [language,base]of Object.entries(bases))for(const chars of [5000,20000,50000]){
   const code=base.repeat(Math.ceil(chars/base.length)).slice(0,chars);const timings=[];
   for(let i=0;i<4;i++)timings.push(window.__benchmarkHighlight(code,language,false));
   timings.shift();timings.sort((a,b)=>a-b);samples.push({language,chars,lines:code.split("\n").length,medianMs:timings[1],maxMs:timings[2]});
  }return samples;
 });
 const giant = 'const huge = "'+"x".repeat(20001)+'";';
 const lineHeavy=Array.from({length:401},()=>"x").join("\n");
 const secondContent=`# Limits and aliases\n\n\`\`\`js\n${giant}\n\`\`\`\n\n\`\`\`py\n${lineHeavy}\n\`\`\`\n\n\`\`\`not-supported\nunknown complete text\n\`\`\`\n\n\`\`\`constructor\nprototype name stays plain\n\`\`\`\n\n\`\`\`js\nconst alias = true;\n\`\`\`\n\n\`\`\`py\nprint("alias")\n\`\`\`\n\nUnicode: İ café 中文 emoji 😀.\n\n\`\`\`ts\nconst eof = 1;\n\`\`\``;
 await page.evaluate(secondContent=>{const doc={path:"D:\\fixtures\\limits.md",name:"limits.md",content:secondContent,revision:"1"};window.__files[doc.path]=doc;window.__nextPath=doc.path;},secondContent);
 await page.getByRole("button",{name:"Open File",exact:true}).click();
 await page.getByRole("button",{name:"Discard",exact:true}).click();await delay(450);
 await page.getByRole("button",{name:"Read",exact:true}).click();await delay(400);
 check("file switch cancels prior preview and shows new document",await page.locator(".markdown-body h1").innerText()==="Limits and aliases"&&await page.locator(".code-block").count()===7);
 const limitCount=(await snapshot()).highlights;
 check("oversize code remains complete plain text",await block(0).locator("code").textContent()===giant&&await block(0).locator(".token").count()===0);
 await block(1).evaluate(el=>el.scrollIntoView());await delay(250);
 check("401-line block remains plain even below character limit",await block(1).locator("code").textContent()===lineHeavy&&await block(1).locator(".token").count()===0);
 await block(5).evaluate(el=>el.scrollIntoView());await delay(300);
 check("unknown and prototype-named languages stay plain",await block(2).locator(".token").count()===0&&await block(3).locator(".token").count()===0);
 check("JS and Python aliases highlight normally",await block(4).locator(".token").count()>0&&await block(5).locator(".token").count()>0);
 await block(0).getByRole("button",{name:"Copy code",exact:true}).click();await delay(300);
 check("oversize code still copies in full",await page.evaluate(()=>window.__copied)===giant);
 await search("const huge");check("oversize plain text is searchable",(await counts())==="1 / 1");
 await search("İ");check("Unicode search keeps valid offsets",(await validRanges()).connected&&(await counts())==="1 / 1");
 await page.keyboard.press("Escape");
 await page.screenshot({path:path.join(dir,"regression.png")});
 const report={checks,inputBurstMs:inputCost,typingMs,geometry,sizes,final:await snapshot()};
 await writeFile(path.join(dir,"regression.json"),JSON.stringify(report,null,2));
 console.log(JSON.stringify(report,null,2));
}
